### ISSUE TITLE
Decidir el lenguaje de programación

### ISSUE THREAD

**Issue by iscoct** [iscoct/cotan#18]
# Preámbulo

El objetivo de este ticket es discutir y especificar determinadas decisiones de diseño para el proyecto, en constante actualización para responder a las necesidades del proyecto.

# Lenguaje propuesto
Se propone [Scala](https://www.scala-lang.org/) como lenguaje principal por poder ejecutarse en muchísimos entornos (se ejecuta por encima de [JVM](https://en.wikipedia.org/wiki/Java_virtual_machine), por su flexibilidad y posibilidad de uso de Java, su eficiencia, tipado estático, programación funcional y uso en Big Data, como Azure Databricks (esto último por la satisfación de aprender un lenguaje nuevo y útil).

## Guía de estilo
Este proyecto seguiría la [guía de estilo oficial de Scala](https://docs.scala-lang.org/style/)

**Comment by iscoct** [comment]
Buenas @arsa-dev, ¿te parece bien si comentamos si es una buena decisión Scala para el proyecto?

He pensado en scala además de lo incluido arriba porque:
1. Tiene bastante soporte entre IDE, lo cual facilita el desarrollo (SCALA IDE, INTELLIJ IDEA, ...).
2. Permite automatización de test de manera sencilla, [aquí se puede ver lo fácil que es hacer el primer test](https://www.scalatest.org/user_guide/writing_your_first_test).
3. Tiene tipado estático y nos permite compilar de manera rápida y frecuente para ver los errores.
4. Permite programación funcional, lo cual nos permite hacer más con menos.
5. Permite usar Java de manera bastante sencilla directamente desde Scala.
6. Lo usan muchas empresas como Databricks, Spotify, ... Se puede ver más empresas [al final de esta página](https://www.scala-lang.org/).
7. Se creó en 2004, lo cual quiere decir que hay bastante documentación al respecto y se siguen sacando actualizaciones (la última hace 8 meses).

Lo malo es lo siguiente:
1. La comunidad en comparación con otros lenguajes como: Python, C/C++, Javascript, ... no es tan grande, por lo que puede ser algo más difícil encontrar soluciones a los problemas que nos encontremos.
2. Puede tener algunos problemas que arrastre Java con su JVM u optimización.

Espero respuesta para que me comentes qué te parece.

**Comment by iscoct** [comment]
Buenas @jmramirezG, he visto que se te ha asignado ahora al final a ti mi proyecto.

Vamos hablando del comentario anterior!

**Comment by jmramirezG** [comment]
Buenas @iscoct!

He estado informándome sobre Scala y he visto lo siguiente:

* Tiene [soporte para vs code](https://marketplace.visualstudio.com/items?itemName=scalameta.metals) lo cual considero una ventaja.
* No es necesario especificar el tipado ya que pese a que sea un lenguaje de tipado estático, el compilador realiza [inferencia de tipos](https://docs.scala-lang.org/tour/type-inference.html#inner-main), por lo que desarrollar en este lenguaje será bastante cómodo.
* A primera vista, me gusta el sistema de tests que has propuesto.

No obstante, hay ciertas cosas que se pueden volver un problema más adelante:

* La mezcla de código Java y Scala puede ser algo confusa.
* Para gran parte de los problemas más complejos que puedan surgir durante el desarrollo, la solución que se encuentre online seguramente contenga código en Java, que no supondrá un problema para la ejecución pero si para el desarrollador.

En general, me parece que Scala es una buena opción, ya que las posibles desventajas son más bien poco probables y, al ser un lenguaje orientado a [resolver problemas concretos](https://www.theserverside.com/feature/Scala-and-the-Cloud) (lo que se conoce como un *DSL*), tiene un gran potencial para el desarrollo de tu aplicación.

Espero tu respuesta!

**Comment by iscoct** [comment]
Muchas gracias por tus consejos @jmramirezG, interesante lo de Java, cierto es que puede ser un lío, más como no se sigan buenas prácticas de programación y hagamos funciones grandes que mezclen código de Java y Scala.

Creo que los inconvenientes si se siguen las buenas prácticas y sentido común podremos evitarlo.

**Comment by iscoct** [comment]
Pues, si lo ves bien igual que yo, cierra este issue y proseguimos con la definición de la estructura de datos.

**Comment by jmramirezG** [comment]
Exacto! Yo creo que los problemas que puedan surgir no serán tan complejos como para tener que recurrir a código ajeno escrito en Java.

Por lo que tengo entendido los issues hay que cerrarlos siempre desde un commit para que pase los tests de la asignatura, pero si, lo damos por cerrado y le hago un fork a tu proyecto.

Abro un nuevo issue para comentar los detalles del [M1](https://github.com/iscoct/cotan/milestone/4)!

**Comment by iscoct** [comment]
Perfecto, @jmramirezG lo cerramos luego desde el commit.

**Comment by iscoct** [comment]
Como ya comentamos por mensajes privados @jmramirezG , crear una API en Scala, no es nada sencillo.

Intenté crear una prueba de concepto con [Akka](https://akka.io/docs/), con [Lagom](https://www.lagomframework.com/documentation/) y [Play Framework](https://www.playframework.com/) y con ninguna de estas librerías y frameworks es sencillo crear un servicio web.
Es así porque da bastante más funcionalidad de la que necesitamos y hace falta aprender bastantes conceptos para poder empezar a trabajar.

Visto esto, tal y como comentamos, he decidido escoger [Go](https://go.dev/) como lenguaje de programación.
Como lenguaje de programción Go:
- Es de tipado estático y es un lenguaje compilado, lo cual reduce errores en la fase de desarrollo.
- Es el lenguaje número 12 más usado según la [encuesta realizada por StackOverflow](https://insights.stackoverflow.com/survey/2020#most-popular-technologies), que si descontamos lenguajes de Front, como HTML/CSS, lenguajes de bases de datos, SQL, y nos quedamos sólo con lenguajes que estén pensados para desarrollar APIs, es el lenguaje número 8 más usado.
- Go ha sido bastante usado tanto en grandes como en pequeños proyectos, como se puede ver [aquí](https://go.dev/solutions/#case-studies).
- Es fácil de aprender entre su [Playground](https://go.dev/play/) y [los cursos online que tiene](https://go.dev/learn/).
- [Gin](https://github.com/gin-gonic/gin) es un framework que hace justo lo que necesitamos en nuestro proyecto, un similar a [Express](https://expressjs.com/) o [Flask](https://flask.palletsprojects.com/en/2.2.x/) que nos permite crear un servidor para crear APIs.
- Go además maneja la concurrencia por ti y tiene recolector de basura.
- Por último, la especialidad según el uso que se le suele dar a Go es la de backends y scripting, por lo que como vamos a hacer un backend en esta asignatura, me parece bastante apropiado.

Si ves algo por lo que no debieramos usar Go, lo seguimos comentado por aquí.

**Comment by jmramirezG** [comment]
Me parece buena idea, además Go tiene una sintaxis bastante simple en comparación con otros lenguajes (que no es que la de Scala sea mucho más complicada, pero a mi me lo parece).

Había escuchado hablar de Gin y me parece un muy buen framework, también hay varias alternativas, como sería [Beego](https://github.com/beego/beego), pero sin dudas Gin tiene más documentación que esta que he mencionado.

Lo dicho entonces, seguimos con Go, por mi parte voy a inicializar el repositorio y a lo largo de estos días y mañana iré cerrando tanto este issue como el issue #19.

**Comment by iscoct** [comment]
Perfecto, no conocía Beego, gracias por compartirlo @jmramirezG
