### ISSUE TITLE
¿Cómo se optimiza el tiempo de salida de los platos de una comanda de cocina?

### ISSUE THREAD

**Issue by jmramirezG** [iscoct/cotan#33]
Con el nombre, tipo (entrante, primero, segundo o postre) y  estado del plato sería suficiente, en mi opinión, para optimizar la salida de los mismos de cocina, ya que los chefs verían el plato a realizar y que tipo es y se pondrían a preparalo.

Espero tu feedback!

**Comment by iscoct** [comment]
Diría que no sólo es necesario eso, nos hace falta:

- Los pasos para los distintos platos, los cuales tendrán un tiempo asociado, quiero decir, cada paso de cada plato tardará un tiempo.
- Un paso, como hornear, normalmente necesita un instrumento, como horno, por tanto este también es importante para el problema, si el horno 1 está ya utilizándose, no se puede utilizar por otra persona.

**Comment by iscoct** [comment]
Los pasos creo que deberían de decir si están empezados o no y los instrumentos si están ocupados o no.

**Comment by iscoct** [comment]
No tengo claro si las comandas o los pasos u otra entidad debería de tener el registro del tiempo que se ha tardado en ejecutar dicho paso, plato o comanda.

**Comment by iscoct** [comment]
La comanda no creo que debería de tener un estado, ni los platos tampoco, porque el estado de la comanda es el conjunto de estados de los platos (si hay un plato preparándose, la comanda se está preparando), ni el plato porque si hay un paso preparándose, el plato se está preparando.

**Comment by iscoct** [comment]
El tiempo de una comanda es el tiempo desde que se pidió la comanda y el tiempo del último plato que se preparó.

El tiempo de un plato es el tiempo desde que se pidió o se empezó a preparar el plato, no lo tengo claro, hasta que se terminó el último paso del plato.

**Comment by iscoct** [comment]
La mesa, los empleados u otras entidades creo que por ahora se podrían obviar.

**Comment by jmramirezG** [comment]
> Los pasos para los distintos platos, los cuales tendrán un tiempo asociado, quiero decir, cada paso de cada plato tardará un tiempo.

Perfecto!

> Un paso, como hornear, normalmente necesita un instrumento, como horno, por tanto este también es importante para el problema, si el horno 1 está ya utilizándose, no se puede utilizar por otra persona.

Genial, se añaden entonces los instrumentos a los pasos de elaboración también.

> La comanda no creo que debería de tener un estado, ni los platos tampoco, porque el estado de la comanda es el conjunto de estados de los platos (si hay un plato preparándose, la comanda se está preparando), ni el plato porque si hay un paso preparándose, el plato se está preparando.

Es decir, el estado debería estar en el paso entonces?

> El tiempo de una comanda es el tiempo desde que se pidió la comanda y el tiempo del último plato que se preparó.

Entonces, el tiempo de una comanda sería la diferencia, no? Tipo cuanto tiempo lleva la comanda "abierta".

> El tiempo de un plato es el tiempo desde que se pidió o se empezó a preparar el plato, no lo tengo claro, hasta que se terminó el último paso del plato.

Diría que el tiempo de un plato debería comenzar cuando se pide, así se podrían priorizar también los platos que se han pedido antes, no? 

Coméntame qué te parece!

**Comment by iscoct** [comment]
> Es decir, el estado debería estar en el paso entonces?

Lo del paso, no digo que esté dentro, pero el estado del plato y la comanda se puede inferir desde el paso diría yo.

> Entonces, el tiempo de una comanda sería la diferencia, no? Tipo cuanto tiempo lleva la comanda "abierta".

La diferencia de qué tiempo a qué tiempo.

> Diría que el tiempo de un plato debería comenzar cuando se pide, así se podrían priorizar también los platos que se han pedido antes, no?

Claro, pero ese tiempo es el tiempo desde que se pidió la comanda y el tiempo actual para todos los platos no preparados.

**Comment by iscoct** [comment]
Otra cosa es, la comanda, ¿si alguien pide nuevos platos, eso forma parte de la comanda original o es una nueva comanda?

**Comment by jmramirezG** [comment]
> La diferencia de qué tiempo a qué tiempo.

Diría que la diferencia entre que se pide el primer elemento de la comanda y que se entrega el último, ese sería el tiempo que ha estado "abierta" la comanda.

> Claro, pero ese tiempo es el tiempo desde que se pidió la comanda y el tiempo actual para todos los platos no preparados.
Otra cosa es, la comanda, ¿si alguien pide nuevos platos, eso forma parte de la comanda original o es una nueva comanda?

No necesariamente el tiempo de un plato coincide con el inicio de la comanda. Si consideramos que si se piden más platos, es la misma comanda, el tiempo debería ser una propiedad del plato, si no, el tiempo sería una propiedad de cada comanda.
Por mi parte, propongo que el tiempo sea parte del plato, así se pueden priorizar dentro de una misma comanda los platos según cuando fueron pedidos y el tiempo de la comanda se puede inferir.

Qué te parece?

**Comment by jmramirezG** [comment]
Una duda más sobre los pasos de elaboración, el tiempo que tiene cada paso es el tiempo que tarda en llevarse a cabo ese paso o tiene algo que ver con el tiempo en el que se empezó/acabó?

**Comment by iscoct** [comment]
> No necesariamente el tiempo de un plato coincide con el inicio de la comanda. Si consideramos que si se piden más platos, es la misma comanda, el tiempo debería ser una propiedad del plato, si no, el tiempo sería una propiedad de cada comanda.
Por mi parte, propongo que el tiempo sea parte del plato, así se pueden priorizar dentro de una misma comanda los platos según cuando fueron pedidos y el tiempo de la comanda se puede inferir.

Okay, destacar que debe tener tiempo inicial pero no tiempo final, pues el tiempo final es el tiempo cuando se termina el último paso del plato.

> Una duda más sobre los pasos de elaboración, el tiempo que tiene cada paso es el tiempo que tarda en llevarse a cabo ese paso o tiene algo que ver con el tiempo en el que se empezó/acabó?

El paso debe tener el tiempo inicial, para saber cuando se empieza, el tiempo esperado para optimizar la secuencia de pasos a hacer y el tiempo final para saber cuando se terminó el paso.

**Comment by jmramirezG** [comment]
Perfecto, pues implemento y lo subo para que le eches un vistazo!
